version: '3'
services:
    client:
        build: './client'
        volumes:
            - ./client:/app
    posts:
        build: './posts'
        volumes:
            - ./posts:/app

    comments:
        build: './comments'
        volumes:
            - ./comments:/app

    query:
        build: './query'
        volumes:
            - ./query:/app

    moderation:
        build: './moderation'
        volumes:
            - ./moderation:/app

    event-bus:
        build: './event-bus'
        volumes:
            - ./event-bus:/app
